---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: Update yum repo and cache
  yum: name=* state=latest
  when: ansible_os_family == 'RedHat'